/**
 * @name Discord Arabic Translator
 * @author IBRA - @IBRUB
 * @description Translates Discord UI text to Arabic (translation only, no layout changes)
 * @version 0.0.1
 * @authorLink https://github.com/IBRHUB
 * @website https://github.com/IBRHUB/DiscordArabicUI
 * @source https://github.com/IBRHUB/DiscordArabicUI
 */

module.exports = class DiscordArabicTranslator {
    constructor(meta) {
        this.meta = meta;
        this.observer = null;
    }

    translateNode(el) {
        if (el.dataset.arTranslated) return;

        if (el.children.length === 0) {
            const txt = el.textContent.trim();
            if (this.dict[txt]) {
                el.textContent = this.dict[txt];
                el.dataset.arTranslated = "1";
            }
        }

        if (el.placeholder && this.dict[el.placeholder]) {
            el.placeholder = this.dict[el.placeholder];
        }

        if (el.title && this.dict[el.title]) {
            el.title = this.dict[el.title];
        }

        if (el.getAttribute("aria-label")) {
            const aria = el.getAttribute("aria-label");
            if (this.dict[aria]) {
                el.setAttribute("aria-label", this.dict[aria]);
            }
        }
    }

    translatePage() {
        document.querySelectorAll("*").forEach((el) => this.translateNode(el));
    }

    start() {
        this.dict = {
    
    "Friends":"الأصدقاء",
    "Add Friend":"إضافة صديق",
    "Online":"متصل",
    "Offline":"غير متصل",
    "Pending":"قيد الانتظار",
    "Blocked":"محظور",
    "All":"الكل",
    
    "Home":"الرئيسية",
    "Messages":"الرسائل",
    "Message":"رسالة",
    "Direct Messages":"الرسائل الخاصة",
    "Search":"بحث",
    
    "Settings":"الإعدادات",
    "User Settings":"إعدادات المستخدم",
    "My Account":"حسابي",
    "Profiles":"الملفات الشخصية",
    "Privacy":"الخصوصية",
    "Security":"الأمان",
    "Authorized Apps":"التطبيقات المصرح بها",
    "Devices":"الأجهزة",
    
    "Voice":"الصوت",
    "Video":"الفيديو",
    "Notifications":"الإشعارات",
    "Appearance":"المظهر",
    "Accessibility":"إمكانية الوصول",
    "Language":"اللغة",
    
    "Servers":"السيرفرات",
    "Channels":"القنوات",
    "Create Channel":"إنشاء قناة",
    "Create Server":"إنشاء سيرفر",
    "Explore Discoverable Servers":"استكشاف السيرفرات",
    
    "Members":"الأعضاء",
    "Bots":"البوتات",
    "Roles":"الرتب",
    "Permissions":"الصلاحيات",
    
    "Invite":"دعوة",
    "Invites":"الدعوات",
    "Copy":"نسخ",
    "Paste":"لصق",
    "Delete":"حذف",
    "Edit":"تعديل",
    "Save":"حفظ",
    "Cancel":"إلغاء",
    
    "Upload":"رفع",
    "Download":"تحميل",
    "Streaming":"بث مباشر",
    "Watch Stream":"مشاهدة البث",
    
    "Mute":"كتم",
    "Unmute":"إلغاء الكتم",
    "Deafen":"تعطيل الصوت",
    "Disconnect":"قطع الاتصال",
    
    "Typing":"يكتب...",
    "Reply":"رد",
    "Replying":"جارٍ الرد",
    "Mark as Read":"تحديد كمقروء",
    
    "Thread":"موضوع",
    "Threads":"المواضيع",
    "Forum":"المنتدى",
    
    "Store":"المتجر",
    "Nitro":"نايترو",
    "Gift":"هدية",
    
    "Login":"تسجيل الدخول",
    "Logout":"تسجيل الخروج",
    "Register":"إنشاء حساب",
    
    "Username":"اسم المستخدم",
    "Password":"كلمة المرور",
    "Email":"البريد الإلكتروني",
    
    "Enable":"تفعيل",
    "Disable":"تعطيل",
    
    "Dark":"داكن",
    "Light":"فاتح",
    
    "Microphone":"الميكروفون",
    "Speaker":"السماعة",
    "Camera":"الكاميرا",
    
    "Stage":"الستيج",
    "Events":"الفعاليات",
    "Create Event":"إنشاء فعالية",
    
    "Help":"مساعدة",
    "Support":"الدعم",
    "Developer":"المطور",
    
    "Connected":"متصل",
    "Connecting":"جارٍ الاتصال",
    "Reconnecting":"إعادة الاتصال",
    
    "Send a message":"أرسل رسالة",
    "Start Video Call":"بدء مكالمة فيديو",
    "Start Voice Call":"بدء مكالمة صوتية",
    
    "New Group DM":"رسالة جماعية جديدة",
    "Add Server":"إضافة سيرفر",
    
    "Explore":"استكشاف",
    "Browse Channels":"تصفح القنوات",
    
    "Friends List":"قائمة الأصدقاء",
    "Activity":"النشاط",
    "Game Activity":"نشاط الألعاب",
    
    "Status":"الحالة",
    "Idle":"خامل",
    "Do Not Disturb":"عدم الإزعاج",
    "Invisible":"مخفي",
    
    "Accept":"قبول",
    "Decline":"رفض",
    
    "Yes":"نعم",
    "No":"لا",
    
    "Today":"اليوم",
    "Yesterday":"أمس",
    
    "Nitro Classic":"نايترو كلاسيك",
    "Nitro Basic":"نايترو بيسك",
    "Subscribe":"اشتراك",
    "Billing":"الفوترة",
    "Subscriptions":"الاشتراكات",
    "Payment Methods":"طرق الدفع",
    "Gift Inventory":"مخزون الهدايا",
    "Boost Server":"تعزيز السيرفر",
    "Server Boost":"تعزيز السيرفر",
    "Boosts":"التعزيزات",
    "Boost":"تعزيز",
    
    "Voice Channel":"قناة صوتية",
    "Text Channel":"قناة نصية",
    "Announcement Channel":"قناة إعلانات",
    "Category":"فئة",
    "Create Category":"إنشاء فئة",
    "Edit Channel":"تعديل القناة",
    "Delete Channel":"حذف القناة",
    "Channel Settings":"إعدادات القناة",
    "Server Settings":"إعدادات السيرفر",
    "Overview":"نظرة عامة",
    "Emoji":"إيموجي",
    "Stickers":"ملصقات",
    "Widget":"أداة",
    "Integrations":"التكاملات",
    "Audit Log":"سجل التدقيق",
    "Bans":"الحظر",
    "Moderation":"الإشراف",
    "Safety Setup":"إعداد الأمان",
    "Community":"المجتمع",
    "Onboarding":"التهيئة",
    "Rules":"القواعد",
    "Welcome Screen":"شاشة الترحيب",
    
    "Pin Message":"تثبيت الرسالة",
    "Unpin Message":"إلغاء تثبيت الرسالة",
    "Pinned Messages":"الرسائل المثبتة",
    "Copy Message Link":"نسخ رابط الرسالة",
    "Copy Text":"نسخ النص",
    "Copy ID":"نسخ المعرّف",
    "Copy Link":"نسخ الرابط",
    "Forward":"إعادة توجيه",
    "React":"تفاعل",
    "Add Reaction":"إضافة تفاعل",
    "Edit Message":"تعديل الرسالة",
    "Delete Message":"حذف الرسالة",
    "Report Message":"الإبلاغ عن الرسالة",
    "Mark Unread":"تحديد كغير مقروء",
    "Speak Message":"قراءة الرسالة",
    
    "Add Note":"إضافة ملاحظة",
    "Remove Friend":"إزالة صديق",
    "Block":"حظر",
    "Unblock":"إلغاء الحظر",
    "Ignore":"تجاهل",
    "Message Request":"طلب رسالة",
    "Spam":"بريد مزعج",
    "Friend Request":"طلب صداقة",
    "Send Friend Request":"إرسال طلب صداقة",
    "View Profile":"عرض الملف الشخصي",
    "User Profile":"الملف الشخصي",
    "About Me":"نبذة عني",
    "Member Since":"عضو منذ",
    
    "Create Invite":"إنشاء دعوة",
    "Invite People":"دعوة أشخاص",
    "Invite to Server":"دعوة إلى السيرفر",
    "Invite Friends":"دعوة الأصدقاء",
    "Copy Invite Link":"نسخ رابط الدعوة",
    "Expires":"ينتهي",
    "Never":"أبدًا",
    "Uses":"الاستخدامات",
    "Max Uses":"الحد الأقصى للاستخدام",
    
    "Join Voice":"الانضمام للصوت",
    "Leave Voice":"مغادرة الصوت",
    "Join":"انضمام",
    "Leave":"مغادرة",
    "Open":"فتح",
    "Close":"إغلاق",
    "Open in Browser":"فتح في المتصفح",
    "Open in App":"فتح في التطبيق",
    "Share Screen":"مشاركة الشاشة",
    "Stop Sharing":"إيقاف المشاركة",
    "Screen Share":"مشاركة الشاشة",
    "Go Live":"بث مباشر",
    "Stop Streaming":"إيقاف البث",
    "Turn On Camera":"تشغيل الكاميرا",
    "Turn Off Camera":"إيقاف الكاميرا",
    "Raise Hand":"رفع اليد",
    "Lower Hand":"خفض اليد",
    
    "Undeafen":"إلغاء تعطيل الصوت",
    "Deafen Server":"تعطيل صوت السيرفر",
    "Mute Server":"كتم السيرفر",
    "Push to Talk":"اضغط للتحدث",
    "Voice Activity":"نشاط الصوت",
    "Input Device":"جهاز الإدخال",
    "Output Device":"جهاز الإخراج",
    "Input Volume":"مستوى الإدخال",
    "Output Volume":"مستوى الإخراج",
    "Echo Cancellation":"إلغاء الصدى",
    "Noise Suppression":"قمع الضوضاء",
    "Advanced":"متقدم",
    
    "Notifications Settings":"إعدادات الإشعارات",
    "Mute Channel":"كتم القناة",
    "Unmute Channel":"إلغاء كتم القناة",
    "Notification Settings":"إعدادات الإشعارات",
    "All Messages":"كل الرسائل",
    "Only @mentions":"الإشارات فقط",
    "Nothing":"لا شيء",
    "Suppress @everyone":"كتم @everyone",
    "Mobile Push Notifications":"إشعارات الجوال",
    
    "Keybinds":"اختصارات المفاتيح",
    "Text & Images":"النص والصور",
    "Streamer Mode":"وضع البث",
    "Advanced Settings":"إعدادات متقدمة",
    "Activity Privacy":"خصوصية النشاط",
    "Registered Games":"الألعاب المسجلة",
    "Overlay":"التراكب",
    "Game Overlay":"تراكب اللعبة",
    "Hardware Acceleration":"تسريع الأجهزة",
    "Open Discord Folder":"فتح مجلد ديسكورد",
    "Log Out":"تسجيل الخروج",
    "Change Password":"تغيير كلمة المرور",
    "Two-Factor Authentication":"المصادقة الثنائية",
    "Enable Two-Factor Auth":"تفعيل المصادقة الثنائية",
    "Phone Number":"رقم الهاتف",
    "Display Name":"الاسم المعروض",
    "Avatar":"الصورة الرمزية",
    "Banner":"اللافتة",
    "Bio":"السيرة",
    "Pronouns":"الضمائر",
    
    "Search Messages":"بحث في الرسائل",
    "Search Members":"بحث في الأعضاء",
    "Search Channels":"بحث في القنوات",
    "No results found":"لم يتم العثور على نتائج",
    "Loading":"جارٍ التحميل",
    "Load More":"تحميل المزيد",
    "Show More":"عرض المزيد",
    "Show Less":"عرض أقل",
    "See All":"عرض الكل",
    "Back":"رجوع",
    "Next":"التالي",
    "Previous":"السابق",
    "Done":"تم",
    "Continue":"متابعة",
    "Confirm":"تأكيد",
    "Apply":"تطبيق",
    "Reset":"إعادة تعيين",
    "Clear":"مسح",
    "Remove":"إزالة",
    "Add":"إضافة",
    "Create":"إنشاء",
    "Update":"تحديث",
    "Refresh":"تحديث",
    "Retry":"إعادة المحاولة",
    "Skip":"تخطي",
    "Learn More":"اعرف المزيد",
    "Get Started":"ابدأ",
    "Try Again":"حاول مرة أخرى",
    
    "Library":"المكتبة",
    "Shop":"المتجر",
    "Quests":"المهام",
    "Discover":"اكتشف",
    "Now Playing":"يعمل الآن",
    "Playing a Game":"يلعب لعبة",
    "Listening to Spotify":"يستمع على سبوتيفاي",
    "Custom Status":"حالة مخصصة",
    "Set a custom status":"تعيين حالة مخصصة",
    "Clear Status":"مسح الحالة",
    "Set Status":"تعيين الحالة",
    "Online Status":"حالة الاتصال",
    
    "Notes":"ملاحظات",
    "Reminders":"تذكيرات",
    "Scheduled Events":"الفعاليات المجدولة",
    "Create Scheduled Event":"إنشاء فعالية مجدولة",
    "Start Time":"وقت البدء",
    "End Time":"وقت الانتهاء",
    "Location":"الموقع",
    "Interested":"مهتم",
    "Not Interested":"غير مهتم",
    
    "Slowmode":"الوضع البطيء",
    "NSFW":"محتوى للبالغين",
    "Age-Restricted Channel":"قناة مقيدة بالعمر",
    "Verification Level":"مستوى التحقق",
    "Explicit Content Filter":"فلتر المحتوى الصريح",
    "Default Notifications":"الإشعارات الافتراضية",
    
    "Manage Roles":"إدارة الرتب",
    "Create Role":"إنشاء رتبة",
    "Edit Role":"تعديل الرتبة",
    "Delete Role":"حذف الرتبة",
    "Display Role Separately":"عرض الرتبة بشكل منفصل",
    "Mentionable":"قابل للإشارة",
    "Hoist":"رفع",
    "Color":"اللون",
    "Administrator":"مسؤول",
    "Manage Server":"إدارة السيرفر",
    "Manage Channels":"إدارة القنوات",
    "Manage Messages":"إدارة الرسائل",
    "Kick Members":"طرد الأعضاء",
    "Ban Members":"حظر الأعضاء",
    "Manage Nicknames":"إدارة الألقاب",
    "Change Nickname":"تغيير اللقب",
    "Nickname":"اللقب",
    "View Audit Log":"عرض سجل التدقيق",
    "View Channels":"عرض القنوات",
    "Send Messages":"إرسال الرسائل",
    "Send TTS Messages":"إرسال رسائل TTS",
    "Embed Links":"تضمين الروابط",
    "Attach Files":"إرفاق الملفات",
    "Read Message History":"قراءة سجل الرسائل",
    "Mention Everyone":"إشارة الجميع",
    "Use External Emojis":"استخدام إيموجي خارجية",
    "Connect":"الاتصال",
    "Speak":"التحدث",
    "Move Members":"نقل الأعضاء",
    "Use Voice Activity":"استخدام نشاط الصوت",
    "Priority Speaker":"متحدث ذو أولوية",
    "Stream":"بث",
    "View Server Insights":"عرض إحصاءات السيرفر",
    
    "Apps":"التطبيقات",
    "App Directory":"دليل التطبيقات",
    "Browse Apps":"تصفح التطبيقات",
    "Add App":"إضافة تطبيق",
    "Remove App":"إزالة التطبيق",
    "Bot":"بوت",
    "Commands":"الأوامر",
    "Slash Commands":"أوامر الشرطة",
    
    "Threads Settings":"إعدادات المواضيع",
    "Create Post":"إنشاء منشور",
    "New Post":"منشور جديد",
    "Post":"نشر",
    "Posts":"المنشورات",
    "Tags":"الوسوم",
    "Sort & View":"الفرز والعرض",
    "Recently Active":"نشط مؤخرًا",
    "Archive":"أرشفة",
    "Unarchive":"إلغاء الأرشفة",
    "Lock Thread":"قفل الموضوع",
    "Unlock Thread":"فتح الموضوع",
    "Join Thread":"الانضمام للموضوع",
    "Leave Thread":"مغادرة الموضوع",
    "Follow":"متابعة",
    "Unfollow":"إلغاء المتابعة",
    
    "Inbox":"صندوق الوارد",
    "Mentions":"الإشارات",
    "For You":"لك",
    "Following":"المتابَع",
    "Favorites":"المفضلة",
    "Saved Messages":"الرسائل المحفوظة",
    "Bookmarks":"الإشارات المرجعية",
    
    "Clip":"مقطع",
    "Clips":"المقاطع",
    "Create Clip":"إنشاء مقطع",
    "Screenshots":"لقطات الشاشة",
    "Media":"الوسائط",
    "Files":"الملفات",
    "Links":"الروابط",
    "GIFs":"صور GIF",
    "Emoji Picker":"منتقي الإيموجي",
    "Sticker Picker":"منتقي الملصقات",
    "Upload a File":"رفع ملف",
    "Drag and drop":"اسحب وأفلت",
    
    "Report":"إبلاغ",
    "Report User":"الإبلاغ عن مستخدم",
    "Report Server":"الإبلاغ عن سيرفر",
    "Trust & Safety":"الثقة والأمان",
    "Feedback":"ملاحظات",
    "What's New":"ما الجديد",
    "Changelog":"سجل التغييرات",
    "Terms of Service":"شروط الخدمة",
    "Privacy Policy":"سياسة الخصوصية",
    "Acknowledgements":"شكر وتقدير",
    "Licenses":"التراخيص",
    "Build Override":"تجاوز البناء",
    "Copy Debug Info":"نسخ معلومات التصحيح",
    
    "Voice Connected":"متصل بالصوت",
    "Voice Disconnected":"غير متصل بالصوت",
    "No Input Detected":"لم يُكتشف إدخال",
    "Weak Connection":"اتصال ضعيف",
    "RTC Connecting":"جارٍ اتصال RTC",
    "Awaiting Endpoint":"في انتظار نقطة النهاية",
    
    "Zoom In":"تكبير",
    "Zoom Out":"تصغير",
    "Fit to Screen":"ملاءمة الشاشة",
    "Fullscreen":"ملء الشاشة",
    "Exit Fullscreen":"الخروج من ملء الشاشة",
    "Pop Out":"نافذة منبثقة",
    "Pop In":"إرجاع للنافذة",
    
    "Group DM":"رسالة جماعية",
    "Start a Group":"بدء مجموعة",
    "Add to Group":"إضافة للمجموعة",
    "Leave Group":"مغادرة المجموعة",
    "Rename Group":"إعادة تسمية المجموعة",
    "Change Icon":"تغيير الأيقونة",
    
    "Server Discovery":"اكتشاف السيرفرات",
    "Featured Communities":"مجتمعات مميزة",
    "Student Hub":"مركز الطلاب",
    "Partnership":"الشراكة",
    "Verified":"موثّق",
    "Partnered":"شريك",
    
    "Email Verified":"البريد موثّق",
    "Phone Verified":"الهاتف موثّق",
    "Verify":"تحقق",
    "Resend":"إعادة الإرسال",
    "Forgot your password?":"نسيت كلمة المرور؟",
    "Reset Password":"إعادة تعيين كلمة المرور",
    "Need an account?":"تحتاج حسابًا؟",
    "Already have an account?":"لديك حساب بالفعل؟",
    "Log In":"تسجيل الدخول",
    "Sign Up":"إنشاء حساب",
    "Welcome back!":"مرحبًا بعودتك!",
    "We're so excited to see you again!":"سعداء برؤيتك مجددًا!",
    
    "This channel is empty.":"هذه القناة فارغة.",
    "Be the first to send a message!":"كن أول من يرسل رسالة!",
    "No messages yet":"لا توجد رسائل بعد",
    "You must be friends to send messages.":"يجب أن تكونوا أصدقاء لإرسال الرسائل.",
    "Unable to load":"تعذّر التحميل",
    "Something went wrong":"حدث خطأ ما",
    "You do not have permission":"ليس لديك صلاحية",
    "Missing Permissions":"صلاحيات ناقصة",
    "Unknown Channel":"قناة غير معروفة",
    "Unknown User":"مستخدم غير معروف",
    "Edited":"معدّل",
    "Pinned":"مثبّت",
    "New":"جديد",
    "NEW":"جديد",
    "Beta":"تجريبي",
    "Experimental":"تجريبي",
    "Preview":"معاينة",
    "Live":"مباشر",
    "Ended":"انتهى",
    "Upcoming":"قادم",
    "Active Now":"نشط الآن",
    "Recently":"مؤخرًا",
    "Earlier":"سابقًا",
    "Jump to Present":"الانتقال للحاضر",
    "New Messages":"رسائل جديدة",
    "You're Viewing Older Messages":"تعرض رسائل أقدم",
    "Beginning of":"بداية",
    "channel history":"سجل القناة",
    
    "Find or start a conversation":"ابحث أو ابدأ محادثة",
    "It's quiet for now...":"الأجواء هادئة الآن...",
    "When a friend starts an activity":"عندما يبدأ صديق نشاطًا",
    "we'll show it here!":"سيظهر هنا!",
    "Active":"نشط",
    "Available":"متاح",
    "Add to Notes":"إضافة للملاحظات",
    "Mute notifications":"كتم الإشعارات",
    "Unmute notifications":"إلغاء كتم الإشعارات",
    "Hide muted channels":"إخفاء القنوات المكتومة",
    "Show muted channels":"إظهار القنوات المكتومة",
    "Collapse":"طي",
    "Expand":"توسيع",
    "Mark As Read":"تحديد كمقروء",
    "Leave Server":"مغادرة السيرفر",
    "Hide":"إخفاء",
    "Show":"إظهار",
    "Copy Username":"نسخ اسم المستخدم",
    "Copy Server ID":"نسخ معرّف السيرفر",
    "Copy Channel ID":"نسخ معرّف القناة",
    "Copy User ID":"نسخ معرّف المستخدم",
    "Timeout":"إيقاف مؤقت",
    "Kick":"طرد",
    "Ban":"حظر",
    "Revoke Ban":"إلغاء الحظر",
    "Transfer Ownership":"نقل الملكية",
    "Delete Server":"حذف السيرفر",
    "Invite to Channel":"دعوة للقناة",
    "Watch":"مشاهدة",
    "Listen Along":"الاستماع معًا",
    "Request to Speak":"طلب التحدث",
    "Stage Channel":"قناة ستيج",
    "Create Stage Channel":"إنشاء قناة ستيج",
    "Audience":"الجمهور",
    "Speakers":"المتحدثون",
    "Listener":"مستمع",
    "Listeners":"المستمعون",
    "Become a Speaker":"كن متحدثًا",
    "Move to Audience":"نقل للجمهور",
    "Open Chat":"فتح الدردشة",
    "Close Chat":"إغلاق الدردشة",
    "User Volume":"مستوى صوت المستخدم",
    "Local Mute":"كتم محلي",
    "Local Deafen":"تعطيل صوت محلي",
    "Voice Settings":"إعدادات الصوت",
    "Video Settings":"إعدادات الفيديو",
    "Automatic":"تلقائي",
    "Legacy":"قديم",
    "Standard":"قياسي",
    "Compact":"مضغوط",
    "Cozy":"مريح",
    "Comfortable":"مريح",
    "Font Scale":"حجم الخط",
    "Zoom Level":"مستوى التكبير",
    "Message Spacing":"تباعد الرسائل",
    "Show Timestamps":"إظهار الوقت",
    "24-Hour Time":"توقيت 24 ساعة",
    "Developer Mode":"وضع المطور",
    "HypeSquad":"هايب سكواد",
    "Connections":"الارتباطات",
    "Linked Roles":"الرتب المرتبطة",
    "Friend Requests":"طلبات الصداقة",
    "Data & Privacy":"البيانات والخصوصية",
    "Delete Account":"حذف الحساب",
    "Disable Account":"تعطيل الحساب",
    "Content & Social":"المحتوى والتواصل",
    "Family Center":"مركز العائلة",
    "Good Standing":"وضع جيد",
    "Limited":"محدود",
    "At Risk":"معرّض للخطر",
    "Violations":"المخالفات",
    "Poll":"استطلاع",
    "Create Poll":"إنشاء استطلاع",
    "Poll Results":"نتائج الاستطلاع",
    "Vote":"تصويت",
    "Votes":"الأصوات",
    "Add Option":"إضافة خيار",
    "Duration":"المدة",
    "Allow Multiple Choices":"السماح بخيارات متعددة",
    "End Poll":"إنهاء الاستطلاع",
    "Text in Voice":"نص في الصوت",
    "Soundboard":"لوحة الأصوات",
    "Open Soundboard":"فتح لوحة الأصوات",
    "Activities":"الأنشطة",
    "Start an Activity":"بدء نشاط",
    "Watch Together":"مشاهدة معًا",
    "Invite to Activity":"دعوة للنشاط",
    "Webhooks":"خطافات الويب",
    "Vanity URL":"رابط مخصص",
    "Server Template":"قالب السيرفر",
    "Enable Community":"تفعيل المجتمع",
    "Disable Community":"تعطيل المجتمع",
    "Insights":"الإحصاءات",
    "Growth":"النمو",
    "Engagement":"التفاعل",
    "Retention":"الاحتفاظ",
    "Server Profile":"ملف السيرفر",
    "Server Tag":"وسم السيرفر",
    "Server Icon":"أيقونة السيرفر",
    "Upload Image":"رفع صورة",
    "Change Avatar":"تغيير الصورة الرمزية",
    "Remove Avatar":"إزالة الصورة الرمزية",
    "Change Banner":"تغيير اللافتة",
    "Remove Banner":"إزالة اللافتة",
    "Accent Color":"لون التمييز",
    "Theme":"السمة",
    "Sync with computer":"مزامنة مع الجهاز",
    "Sync With Computer":"مزامنة مع الجهاز",
    "Muted":"مكتوم",
    "Deafened":"صوت معطّل",
    "Sharing":"يشارك",
    "In a call":"في مكالمة",
    "In a voice channel":"في قناة صوتية",
    "In voice":"في الصوت",
    "Ring":"رنين",
    "Ringing":"يرن...",
    "Call":"مكالمة",
    "Start Call":"بدء مكالمة",
    "End Call":"إنهاء المكالمة",
    "Answer":"رد",
    "Decline Call":"رفض المكالمة",
    "Missed Call":"مكالمة فائتة",
    "Incoming Call":"مكالمة واردة",
    "Outgoing Call":"مكالمة صادرة",
    "User":"مستخدم",
    "Users":"المستخدمون",
    "Owner":"المالك",
    "Moderator":"مشرف",
    "Timed Out":"موقوف مؤقتًا",
    "Communication Disabled":"التواصل معطّل",
    "Remove Timeout":"إلغاء الإيقاف المؤقت",
    "Reason":"السبب",
    "Sticker":"ملصق",
    "GIF":"صورة متحركة",
    "Search GIFs":"بحث عن GIF",
    "Frequently Used":"المستخدمة كثيرًا",
    "Server Emojis":"إيموجي السيرفر",
    "Upload Emoji":"رفع إيموجي",
    "Upload Sticker":"رفع ملصق",
    "Avatar Decorations":"زينة الصورة الرمزية",
    "Profile Effects":"تأثيرات الملف",
    "Nameplate":"لوحة الاسم",
    "Edit Profile":"تعديل الملف",
    "App Settings":"إعدادات التطبيق",
    "Voice & Video":"الصوت والفيديو",
    "Chat":"الدردشة",
    "Input":"إدخال",
    "Output":"إخراج",
    "Video Background":"خلفية الفيديو",
    "Blur":"ضبابية",
    "Custom Background":"خلفية مخصصة",
    "None":"لا شيء",
    "Default":"افتراضي",
    "Custom":"مخصص",
    "Browse":"تصفح",
    "Select":"اختيار",
    "Selected":"محدّد",
    "Optional":"اختياري",
    "Required":"مطلوب",
    "Public":"عام",
    "Private":"خاص",
    "Share":"مشاركة",
    "Send":"إرسال",
    "Sending":"جارٍ الإرسال",
    "Sent":"تم الإرسال",
    "Failed":"فشل",
    "Unread":"غير مقروء",
    "Everyone":"الجميع",
    "Here":"هنا",
    "Role":"رتبة",
    "Add Role":"إضافة رتبة",
    "Remove Role":"إزالة رتبة",
    "Assign Roles":"تعيين الرتب",
    "Unlink":"فك الربط",
    "Connect Account":"ربط الحساب",
    "Disconnect Account":"فك ربط الحساب",
    "Scan QR Code":"مسح رمز QR",
    "Backup Codes":"رموز النسخ الاحتياطي",
    "Passkey":"مفتاح مرور",
    "Passkeys":"مفاتيح المرور",
    "Remember Me":"تذكرني",
    "QR Code Login":"تسجيل دخول برمز QR",
    "Download Discord":"تحميل ديسكورد",
    "Open Discord":"فتح ديسكورد",
    "Check for Updates":"التحقق من التحديثات",
    "Restart":"إعادة التشغيل",
    "Minimize":"تصغير",
    "Maximize":"تكبير",
    "Quit":"خروج",
    "About":"حول",
    "Version":"الإصدار",
    "Are you sure?":"هل أنت متأكد؟",
    "This action cannot be undone.":"لا يمكن التراجع عن هذا الإجراء.",
    "Proceed":"متابعة",
    "Discard":"تجاهل",
    "Discard Changes":"تجاهل التغييرات",
    "Save Changes":"حفظ التغييرات",
    "Unsaved Changes":"تغييرات غير محفوظة",
    "Don't Save":"عدم الحفظ",
    "Keep Editing":"متابعة التعديل",
    "Clone Channel":"نسخ القناة",
    "Clone":"نسخ",
    "Move Channel":"نقل القناة",
    "Create Voice Channel":"إنشاء قناة صوتية",
    "Create Text Channel":"إنشاء قناة نصية",
    "Create Forum Channel":"إنشاء قناة منتدى",
    "Forum Channel":"قناة منتدى",
    "Media Channel":"قناة وسائط",
    "Announcement":"إعلان",
    "Text":"نص",
    "Lock Permissions":"قفل الصلاحيات",
    "Unlock Permissions":"فتح الصلاحيات",
    "Sync Permissions":"مزامنة الصلاحيات",
    "View Channel":"عرض القناة",
    "Deny":"رفض",
    "Allow":"سماح",
    "Inherit":"وراثة",
    "On":"تشغيل",
    "Off":"إيقاف",
    "Enabled":"مفعّل",
    "Disabled":"معطّل",
    "Sort by":"ترتيب حسب",
    "Sort By":"ترتيب حسب",
    "Alphabetical":"أبجدي",
    "Newest":"الأحدث",
    "Oldest":"الأقدم",
    "Popular":"شائع",
    "Recommended":"موصى به",
    "Suggested Friends":"أصدقاء مقترحون",
    "People you may know":"أشخاص قد تعرفهم",
    "Add by Username":"إضافة باسم المستخدم",
    "Enter Username":"أدخل اسم المستخدم",
    "User not found":"المستخدم غير موجود",
    "Rate limited":"تم تجاوز الحد",
    "Slowmode is enabled":"الوضع البطيء مفعّل",
    "just now":"الآن",
    "Just now":"الآن",
    "Now":"الآن",
    "Schedule Message":"جدولة رسالة",
    "Send Later":"إرسال لاحقًا",
    "Set Reminder":"تعيين تذكير",
    "Remind Me":"ذكّرني",
    "Remind me":"ذكّرني",
    "1 Hour":"ساعة واحدة",
    "4 Hours":"4 ساعات",
    "Custom Time":"وقت مخصص",
    "Hand raised":"اليد مرفوعة",
    "Hand Raised":"اليد مرفوعة",
    "Speaking":"يتحدث",
    "Server muted":"مكتوم من السيرفر",
    "Server deafened":"صوت معطّل من السيرفر",
    "Push To Talk":"اضغط للتحدث",
    "Test Microphone":"اختبار الميكروفون",
    "Let's Check":"لنتحقق",
    "AutoMod":"الإشراف التلقائي",
    "Auto Moderation":"الإشراف التلقائي",
    "Block Message":"حظر الرسالة",
    "Send Alert":"إرسال تنبيه",
    "Timeout User":"إيقاف المستخدم مؤقتًا",
    "Member Screening":"فحص الأعضاء",
    "Agree to Rules":"الموافقة على القواعد",
    "I agree":"أوافق",
    "I Agree":"أوافق",
    "Verification":"التحقق",
    "Reaction Role":"رتبة بالتفاعل",
    "Server Guide":"دليل السيرفر",
    "Crosspost":"إعادة نشر",
    "Follow Channel":"متابعة القناة",
    "News Channel":"قناة أخبار",
    "Create Webhook":"إنشاء خطاف ويب",
    "Add Bot":"إضافة بوت",
    "Authorize":"تفويض",
    "Revoke":"إلغاء",
    "Level":"المستوى",
    "Perks":"المزايا",
    "Spoiler":"حرق",
    "Mark as spoiler":"تحديد كحرق",
    "Alt Text":"نص بديل",
    "Add Alt Text":"إضافة نص بديل",
    "Reduce Motion":"تقليل الحركة",
    "Create Thread":"إنشاء موضوع",
    "Create thread":"إنشاء موضوع",
    "Thread Name":"اسم الموضوع",
    "Private Thread":"موضوع خاص",
    "Public Thread":"موضوع عام",
    "Slow Mode":"الوضع البطيء",
    "Locked":"مقفل",
    "Unlocked":"مفتوح",
    "Archived":"مؤرشف",
    "No posts yet":"لا منشورات بعد",
    "Be the first to post!":"كن أول من ينشر!",
    "View Post":"عرض المنشور",
    "Reply in Thread":"الرد في الموضوع",
    "More Replies":"مزيد من الردود",
    "Boost this server":"عزّز هذا السيرفر",
    "Gift a Boost":"إهداء تعزيز",
    "HD Streaming":"بث عالي الدقة",
    "Larger Uploads":"رفع ملفات أكبر",
    "Collections":"المجموعات",
    "Effects":"التأثيرات",
    "Decorate":"تزيين",
    "Inventory":"المخزون",
    "Equip":"تجهيز",
    "Unequip":"إزالة التجهيز",
    "Purchase":"شراء",
    "Buy":"شراء",
    "Free":"مجاني",
    "Owned":"مملوك",
    "Unlock":"فتح",
    "Claim":"استلام",
    "Reward":"مكافأة",
    "Rewards":"المكافآت",
    "Complete Quest":"إكمال المهمة",
    "Progress":"التقدم",
    "Blocked Users":"المستخدمون المحظورون",
    "Message Requests":"طلبات الرسائل",
    "Friends of Friends":"أصدقاء الأصدقاء",
    "Server Members":"أعضاء السيرفر",
    "Nobody":"لا أحد",
    "Report a Bug":"الإبلاغ عن خطأ",
    "Help Center":"مركز المساعدة",
    "Submit":"إرسال",
    "Thank you":"شكرًا",
    "Thanks":"شكرًا",
    "Got it":"فهمت",
    "OK":"موافق",
    "Okay":"حسنًا",
    "Dismiss":"إغلاق",
    "Not now":"ليس الآن",
    "Maybe later":"ربما لاحقًا",
    "Don't show again":"عدم الإظهار مجددًا",
    "Turn on":"تشغيل",
    "Turn off":"إيقاف",
    "Entire Screen":"الشاشة كاملة",
    "Application Window":"نافذة التطبيق",
    "Include audio":"تضمين الصوت",
    "Stream Quality":"جودة البث",
    "Resolution":"الدقة",
    "Frame Rate":"معدل الإطارات",
    "Viewers":"المشاهدون",
    "Watching":"يشاهد",
    "Join Stream":"الانضمام للبث",
    "Leave Stream":"مغادرة البث",
    "Open Profile":"فتح الملف",
    "Return to Call":"العودة للمكالمة",
    "Move to":"نقل إلى",
    "Move to Channel":"نقل للقناة",
    "Disconnect User":"قطع اتصال المستخدم",
    "Move User":"نقل المستخدم",
    "Channel Status":"حالة القناة",
    "Set a channel status":"تعيين حالة القناة",
    "Only visible to you":"مرئي لك فقط",
    "This interaction failed":"فشل التفاعل",
    "Select an option":"اختر خيارًا",
    "Please wait":"يرجى الانتظار",
    "Calling":"يتصل...",
    "No answer":"لا رد",
    "Busy":"مشغول",
    "Unavailable":"غير متاح",
    "For 30 minutes":"لمدة 30 دقيقة",
    "For 1 hour":"لمدة ساعة",
    "Notifications paused":"الإشعارات متوقفة",
    "Favorite":"مفضلة",
    "Unfavorite":"إزالة من المفضلة",
    "Happening Now":"يحدث الآن",
    "Going":"سيحضر",
    "Not Going":"لن يحضر",
    "Maybe":"ربما",
    "Share Event":"مشاركة الفعالية",
    "Canceled":"ملغاة",
    "Cancelled":"ملغاة",
    "Apply to Join":"طلب الانضمام",
    "Pending Review":"قيد المراجعة",
    "Approved":"مقبول",
    "Rejected":"مرفوض",
    "Approve":"قبول",
    "Review":"مراجعة",
    "Member":"عضو",
    "Online Members":"الأعضاء المتصلون",
    "Member List":"قائمة الأعضاء",
    "Filter":"تصفية",
    "Filters":"الفلاتر",
    "Clear filters":"مسح الفلاتر",
    "Sort":"ترتيب",
    "Join a Server":"انضم لسيرفر",
    "Have an invite already?":"لديك دعوة بالفعل؟",
    "Enter an invite link":"أدخل رابط الدعوة",
    "Invite expired":"انتهت صلاحية الدعوة",
    "Invite invalid":"دعوة غير صالحة",
    "Welcome to":"مرحبًا بك في",
    "You're all set":"أنت جاهز",
    "All done":"تم كل شيء",
    "Welcome":"مرحبًا",
    "Say hi":"قل مرحبًا",
    "Super Reaction":"تفاعل خارق",
    "Get Nitro":"احصل على نايترو",
    "Upgrade":"ترقية",
    "Upgrade to Nitro":"الترقية لنايترو",
    "Try Nitro":"جرّب نايترو",
    "Gift Nitro":"إهداء نايترو",
    "Monthly":"شهري",
    "Yearly":"سنوي",
    "Current plan":"الخطة الحالية",
    "Redeem":"استبدال",
    "Enter code":"أدخل الرمز",
    "Log out of all devices":"تسجيل الخروج من كل الأجهزة",
    "Active sessions":"الجلسات النشطة",
    "Last active":"آخر نشاط",
    "Was this you?":"هل هذا أنت؟",
    "Secure your account":"أمّن حسابك",
    "Check your email":"تحقق من بريدك",
    "Check your inbox":"تحقق من صندوق الوارد",
    "Continue to Discord":"المتابعة إلى ديسكورد",
    "Content warning":"تحذير محتوى",
    "Show anyway":"إظهار على أي حال",
    "Date of Birth":"تاريخ الميلاد",
    "Birthday":"عيد الميلاد",
    "Country":"البلد",
    "Time zone":"المنطقة الزمنية",
    "Select language":"اختر اللغة",
    "Translate":"ترجمة",
    "Show original":"إظهار الأصل",
    "Translated":"مترجم",
    "Enable overlay":"تفعيل التراكب",
    "Disable overlay":"تعطيل التراكب",
    "Leaderboard":"لوحة المتصدرين",
    "Completed":"مكتمل",
    "In progress":"قيد التقدم",
    "Expired":"منتهي",
    "Starts soon":"يبدأ قريبًا",
    "Add friend":"إضافة صديق",
    "Log out":"تسجيل الخروج",
    "Mark as read":"تحديد كمقروء",
    "Type a message":"اكتب رسالة",
    "Message #":"رسالة #",
    "Create My Own":"إنشاء سيرفر خاص",
    "For me and my friends":"لي ولأصدقائي",
    "For a club or community":"لنادي أو مجتمع",
    "Gaming":"ألعاب",
    "Study Group":"مجموعة دراسة",
    "Artists & Creators":"فنانون ومبدعون",
    "Local Community":"مجتمع محلي",
    "Global Community":"مجتمع عالمي",
    "Skip for now":"تخطي الآن",
    "Setup complete":"اكتمل الإعداد",
    "Take a tour":"جولة تعريفية",
    "Finish":"إنهاء",
    "Customize your server":"خصص سيرفرك",
    "Personalize your server":"خصّص سيرفرك",
    "Upload a server icon":"ارفع أيقونة السيرفر",
    "How will you use this server?":"كيف ستستخدم هذا السيرفر؟",
    "Nitro tab":"نايترو",
    "Wallet":"المحفظة",
    "Billing Settings":"إعدادات الفوترة",
    "Manage Subscription":"إدارة الاشتراك",
    "Server Folder":"مجلد السيرفرات",
    "Create Folder":"إنشاء مجلد",
    "Folder Settings":"إعدادات المجلد",
    "Folder Name":"اسم المجلد",
    "Color Tag":"لون الوسم",
    "Mark Server as Read":"تحديد السيرفر كمقروء",
    "Notification Override":"تجاوز الإشعارات",
    "Only mentions":"الإشارات فقط",
    "Mobile Push":"إشعارات الجوال",
    "Suppress Everyone":"كتم everyone",
    "Suppress Roles":"كتم الرتب",
    "Privacy Mode":"وضع الخصوصية",
    "Streamer Mode Enabled":"وضع البث مفعّل",
    "Hide Personal Information":"إخفاء المعلومات الشخصية",
    "Disable Sounds":"تعطيل الأصوات",
    "Disable Notifications":"تعطيل الإشعارات",
    "Copy Voice Channel Link":"نسخ رابط القناة الصوتية",
    "Open Voice Channel":"فتح القناة الصوتية",
    "Browse Channels":"تصفح القنوات",
    "Channel Browser":"متصفح القنوات",
    "Browse Topics":"تصفح المواضيع",
    "Create Topic":"إنشاء موضوع",
    "Topic":"الموضوع",
    "Guidelines Channel":"قناة الإرشادات",
    "Rules Channel":"قناة القواعد",
    "Updates Channel":"قناة التحديثات",
    "System Messages Channel":"قناة رسائل النظام",
    "AFK Channel":"قناة AFK",
    "AFK Timeout":"مهلة AFK",
    "System Channel":"قناة النظام",
    "Widget Channel":"قناة الأداة",
    "Boost Level":"مستوى التعزيز",
    "Boost Count":"عدد التعزيزات",
    "See Boost Perks":"عرض مزايا التعزيز",
    "Role Icons":"أيقونات الرتب",
    "Custom Invite Link":"رابط دعوة مخصص",
    "Animated Icon":"أيقونة متحركة",
    "Upload Limit":"حد الرفع",
    "Bitrate Cap":"سقف معدل البت",
    "Emoji Limit":"حد الإيموجي",
    "Sticker Limit":"حد الملصقات",
    "Soundboard Limit":"حد لوحة الأصوات",
    "Browse Channels":"تصفح القنوات",
    "Edit Server Profile":"تعديل ملف السيرفر",
    "Server Emotes":"إيموجي السيرفر",
    "Upload Emote":"رفع إيموجي",
    "Require Tag":"يتطلب وسم",
    "Require Role":"يتطلب رتبة",
    "Allowed Roles":"الرتب المسموحة",
    "Denied Roles":"الرتب المرفوضة",
    "Add Members":"إضافة أعضاء",
    "Remove Members":"إزالة أعضاء",
    "Prune Members":"تنظيف الأعضاء",
    "Prune":"تنظيف",
    "Days of Inactivity":"أيام عدم النشاط",
    "Include roles":"تضمين الرتب",
    "Preview prune":"معاينة التنظيف",
    "Prune Members":"تنظيف الأعضاء",
    "Audit Log Filters":"فلاتر سجل التدقيق",
    "Action":"إجراء",
    "Target":"الهدف",
    "Executor":"المنفّذ",
    "Changes":"التغييرات",
    "Filter by user":"تصفية حسب المستخدم",
    "Filter by action":"تصفية حسب الإجراء",
    "Export Audit Log":"تصدير سجل التدقيق",
    "Ban IP":"حظر عنوان IP",
    "Revoke Invite":"إلغاء الدعوة",
    "Pause Invites":"إيقاف الدعوات مؤقتًا",
    "Pause Invite":"إيقاف الدعوة",
    "Grant Temporary Membership":"عضوية مؤقتة",
    "Grant temporary membership":"عضوية مؤقتة",
    "Incognito":"تخفي",
    "Open Voice Settings":"فتح إعدادات الصوت",
    "Open Video Settings":"فتح إعدادات الفيديو",
    "Noise Reduction":"تقليل الضوضاء",
    "Studio":"استوديو",
    "Open Overlay":"فتح التراكب",
    "Toggle Mute":"تبديل الكتم",
    "Toggle Deafen":"تبديل تعطيل الصوت",
    "User Settings":"إعدادات المستخدم",
    "App Directory":"دليل التطبيقات",
    "Quest Log":"سجل المهام",
    "Claim Quest":"استلام المهمة",
    "Watch Clip":"مشاهدة المقطع",
    "Save Clip":"حفظ المقطع",
    "Delete Clip":"حذف المقطع",
    "Share Clip":"مشاركة المقطع",
    "Copy Clip Link":"نسخ رابط المقطع",
    "Open Clips Folder":"فتح مجلد المقاطع",
    "Record":"تسجيل",
    "Stop Recording":"إيقاف التسجيل",
    "Screenshare":"مشاركة الشاشة",
    "Camera On":"الكاميرا مفعّلة",
    "Camera Off":"الكاميرا متوقفة",
    "Start Video":"بدء الفيديو",
    "Stop Video":"إيقاف الفيديو",
    "Invite to Voice":"دعوة للصوت",
    "Switch Channels":"تبديل القنوات",
    "Browse Voice Channels":"تصفح القنوات الصوتية",
    "Set Status Channel":"تعيين قناة الحالة",
    "Browse Public Servers":"تصفح السيرفرات العامة",
    "Featured":"مميز",
    "Categories":"الفئات",
    "Gaming Servers":"سيرفرات الألعاب",
    "Music Servers":"سيرفرات الموسيقى",
    "Education":"تعليم",
    "Science & Tech":"علوم وتقنية",
    "Entertainment":"ترفيه",
    "Student":"طالب",
    "Campus":"الحرم",
    "Verify Student":"التحقق كطالب",
    "Email Domain":"نطاق البريد",
    "School":"المدرسة",
    "University":"الجامعة",
    "Graduation Year":"سنة التخرج",
    "Major":"التخصص",
    "Submit Verification":"إرسال التحقق",
    "Verification Pending":"التحقق قيد الانتظار",
    "Verified Student":"طالب موثّق",
    "Copy Student Hub Link":"نسخ رابط مركز الطلاب",
    "Partner Program":"برنامج الشركاء",
    "Apply Now":"قدّم الآن",
    "Server Insights":"إحصاءات السيرفر",
    "Enable Monetization":"تفعيل الربح",
    "Creator Portal":"بوابة المبدعين",
    "Payouts":"المدفوعات",
    "Earnings":"الأرباح",
    "Analytics Dashboard":"لوحة التحليلات",
    "Server Subscriptions":"اشتراكات السيرفر",
    "Subscribe to Server":"الاشتراك في السيرفر",
    "Tier":"المستوى",
    "Benefits":"المزايا",
    "Subscriber":"مشترك",
    "Subscribers":"المشتركون",
    "Manage Benefits":"إدارة المزايا",
    "Create Tier":"إنشاء مستوى",
    "Edit Tier":"تعديل المستوى",
    "Delete Tier":"حذف المستوى",
    "Role Benefit":"ميزة الرتبة",
    "Custom Benefits":"مزايا مخصصة",
    "Emote Benefits":"مزايا الإيموجي",
    "Badge":"شارة",
    "Badges":"الشارات",
    "Profile Badge":"شارة الملف",
    "Collectible":"قابل للجمع",
    "Orbs":"أوربس",
    "Decorate Profile":"تزيين الملف",
    "Profile Shop":"متجر الملف",
    "Avatar Shop":"متجر الصور الرمزية",
    "Browse Shop":"تصفح المتجر",
    "Limited Edition":"إصدار محدود",
    "Seasonal":"موسمي",
    "Holiday":"عطلة",
    "Spring":"ربيع",
    "Summer":"صيف",
    "Fall":"خريف",
    "Winter":"شتاء",
    "Halloween":"هالوين",
    "Christmas":"عيد الميلاد",
    "New Year":"رأس السنة",
    "Valentine":"عيد الحب",
    "Easter":"عيد الفصح",
    "Pride":"فخر",
    "Lunar New Year":"رأس السنة القمرية",
    "Anniversary":"ذكرى",
    "Birthday Quest":"مهمة عيد الميلاد",
    "Friend Anniversary":"ذكرى الصداقة",
    "Account Age":"عمر الحساب",
    "Joined Discord":"انضم لديسكورد",
    "Mutual Servers":"سيرفرات مشتركة",
    "Mutual Friends":"أصدقاء مشتركون",
    "Mutual Groups":"مجموعات مشتركة",
    "No mutual friends":"لا أصدقاء مشتركين",
    "No mutual servers":"لا سيرفرات مشتركة",
    "Add Friend on Discord":"إضافة صديق على ديسكورد",
    "Send Message":"إرسال رسالة",
    "Start DM":"بدء رسالة خاصة",
    "Open DM":"فتح الرسائل الخاصة",
    "Close DM":"إغلاق الرسائل الخاصة",
    "Pin DM":"تثبيت المحادثة",
    "Unpin DM":"إلغاء تثبيت المحادثة",
    "Close DM Group":"إغلاق المجموعة",
    "Rename":"إعادة تسمية",
    "Change Nickname":"تغيير اللقب",
    "Edit Server Nickname":"تعديل لقب السيرفر",
    "Server-specific nickname":"لقب خاص بالسيرفر",
    "Clear Nickname":"مسح اللقب",
    "Copy Display Name":"نسخ الاسم المعروض",
    "Copy Global Name":"نسخ الاسم العام",
    "Apps on Profile":"التطبيقات على الملف",
    "Connections on Profile":"الارتباطات على الملف",
    "Note":"ملاحظة",
    "Edit Note":"تعديل الملاحظة",
    "Clear Note":"مسح الملاحظة",
    "Relationship":"العلاقة",
    "Friend":"صديق",
    "Pending Incoming":"طلب وارد",
    "Pending Outgoing":"طلب صادر",
    "Incoming Friend Request":"طلب صداقة وارد",
    "Outgoing Friend Request":"طلب صداقة صادر",
    "Blocked User":"مستخدم محظور",
    "Ignored User":"مستخدم متجاهل",
    "Spam Request":"طلب مزعج",
    "Accept Request":"قبول الطلب",
    "Ignore Request":"تجاهل الطلب",
    "Block User":"حظر المستخدم",
    "Unfriend":"إلغاء الصداقة",
    "Report Spam":"الإبلاغ عن بريد مزعج",
    "Safety Check":"فحص الأمان",
    "Suspicious Link":"رابط مشبوه",
    "Malicious Link":"رابط ضار",
    "Phishing":"تصيّد",
    "Scam":"احتيال",
    "Do not open":"لا تفتح",
    "Trust this link":"الثقة بهذا الرابط",
    "Open Link":"فتح الرابط",
    "Copy Link":"نسخ الرابط",
    "Open in new tab":"فتح في تبويب جديد",
    "Embed":"تضمين",
    "Remove Embed":"إزالة التضمين",
    "Show embeds":"إظهار التضمينات",
    "Hide embeds":"إخفاء التضمينات",
    "Link Settings":"إعدادات الروابط",
    "Instant View":"عرض فوري",
    "Website Preview":"معاينة الموقع",
    "Open Original":"فتح الأصل",
    "Download File":"تحميل الملف",
    "Open File":"فتح الملف",
    "Save As":"حفظ باسم",
    "Open Folder":"فتح المجلد",
    "Show in Folder":"إظهار في المجلد",
    "File Info":"معلومات الملف",
    "Image Tools":"أدوات الصورة",
    "Crop":"قص",
    "Rotate":"تدوير",
    "Flip":"قلب",
    "Zoom":"تكبير",
    "Reset Zoom":"إعادة التكبير",
    "Open in Viewer":"فتح في العارض",
    "Previous Image":"الصورة السابقة",
    "Next Image":"الصورة التالية",
    "Download Image":"تحميل الصورة",
    "Copy Image":"نسخ الصورة",
    "Copy Image Link":"نسخ رابط الصورة",
    "Search with Google":"البحث بجوجل",
    "Search with Bing":"البحث ببينج",
    "Add to Favorites":"إضافة للمفضلة",
    "Remove from Favorites":"إزالة من المفضلة",
    "Pin to Top":"تثبيت في الأعلى",
    "Unpin from Top":"إلغاء التثبيت من الأعلى",
    "Slowmode Off":"الوضع البطيء متوقف",
    "Slowmode On":"الوضع البطيء مفعّل",
    "Rate Limit":"حد المعدل",
    "Cooldown":"مهلة الانتظار",
    "Wait before sending":"انتظر قبل الإرسال",
    "You are sending messages too quickly":"ترسل الرسائل بسرعة كبيرة",
    "Hold up":"انتظر قليلًا",
    "Nitro required":"يتطلب نايترو",
    "Boost required":"يتطلب تعزيزًا",
    "Verification required":"يتطلب تحققًا",
    "Phone verification required":"يتطلب تحقق الهاتف",
    "Email verification required":"يتطلب تحقق البريد",
    "Complete verification to continue":"أكمل التحقق للمتابعة",
    "Read and agree to the rules":"اقرأ القواعد ووافق عليها",
    "You have been timed out":"تم إيقافك مؤقتًا",
    "You cannot send messages in this channel":"لا يمكنك الإرسال في هذه القناة",
    "You cannot view this channel":"لا يمكنك عرض هذه القناة",
    "This channel is read-only":"هذه القناة للقراءة فقط",
    "Only moderators can send messages":"المشرفون فقط يمكنهم الإرسال",
    "Only you can see this message":"أنت فقط ترى هذه الرسالة",
    "Ephemeral message":"رسالة مؤقتة",
    "System Message":"رسالة نظام",
    " joined the server":" انضم للسيرفر",
    " left the server":" غادر السيرفر",
    " pinned a message":" ثبّت رسالة",
    " started a call":" بدأ مكالمة",
    " started a thread":" بدأ موضوعًا",
    " boosted the server":" عزّز السيرفر",
    " created this channel":" أنشأ هذه القناة",
    " changed the channel name":" غيّر اسم القناة",
    "Welcome message":"رسالة ترحيب",
    "Rules accepted":"تم قبول القواعد",
    "Verification complete":"اكتمل التحقق",
    "Loading channels":"جارٍ تحميل القنوات",
    "Loading messages":"جارٍ تحميل الرسائل",
    "Connecting to voice":"جارٍ الاتصال بالصوت",
    "Reconnecting to voice":"إعادة الاتصال بالصوت",
    "Voice connection lost":"فُقد اتصال الصوت",
    "No one is speaking":"لا أحد يتحدث",
    "No one in voice":"لا أحد في الصوت",
    "Empty channel":"قناة فارغة",
    "Join to listen":"انضم للاستماع",
    "Listen In":"استمع",
    "Spectate Stream":"مشاهدة البث",
    "Open Activity":"فتح النشاط",
    "End Activity":"إنهاء النشاط",
    "Leave Activity":"مغادرة النشاط",
    "Activity Invite":"دعوة نشاط",
    "Playing":"يلعب",
    "Watching":"يشاهد",
    "Competing":"يتنافس",
    "Custom":"مخصص",
    "Rich Presence":"حالة غنية",
    "Game Details":"تفاصيل اللعبة",
    "Party":"فريق",
    "Join Party":"انضم للفريق",
    "Ask to Join Party":"طلب الانضمام للفريق",
    "Party Full":"الفريق ممتلئ",
    "Party Locked":"الفريق مقفل",
    "Open Game":"فتح اللعبة",
    "Launch Game":"تشغيل اللعبة",
    "Install Game":"تثبيت اللعبة",
    "Not installed":"غير مثبت",
    "Playing on":"يلعب على",
    "Listening on":"يستمع على",
    "Competing in":"يتنافس في",
    "Use Activity":"استخدام النشاط",
    "Browse Activities":"تصفح الأنشطة",
    "Featured Activities":"أنشطة مميزة",
    "Recently Played":"لُعب مؤخرًا",
    "Favorites":"المفضلة",
    "Apps & Activities":"التطبيقات والأنشطة",
    "Installed Apps":"التطبيقات المثبتة",
    "Manage Installed Apps":"إدارة التطبيقات المثبتة",
    "Integrations Settings":"إعدادات التكاملات",
    "Bot Permissions":"صلاحيات البوت",
    "Custom Commands":"أوامر مخصصة",
    "Command":"أمر",
    "Parameter":"معامل",
    "Parameters":"المعاملات",
    "Required Parameters":"معاملات مطلوبة",
    "Optional Parameters":"معاملات اختيارية",
    "Execute":"تنفيذ",
    "Run Command":"تشغيل الأمر",
    "Command ran successfully":"تم تنفيذ الأمر بنجاح",
    "Interaction timed out":"انتهت مهلة التفاعل",
    "Button":"زر",
    "Buttons":"أزرار",
    "Select Menu":"قائمة اختيار",
    "Modal":"نافذة",
    "Form":"نموذج",
    "Text Input":"إدخال نص",
    "Short":"قصير",
    "Paragraph":"فقرة",
    "Number Input":"إدخال رقم",
    "Checkbox":"مربع اختيار",
    "Radio":"اختيار واحد",
    "Switch":"مفتاح",
    "Slider":"منزلق",
    "Color Picker":"منتقي الألوان",
    "Date Picker":"منتقي التاريخ",
    "Time Picker":"منتقي الوقت",
    "File Upload":"رفع ملف",
    "Image Upload":"رفع صورة",
    "Video Upload":"رفع فيديو",
    "Audio Upload":"رفع صوت",
    "Maximum file size":"الحد الأقصى لحجم الملف",
    "File type not supported":"نوع الملف غير مدعوم",
    "Upload failed":"فشل الرفع",
    "Upload complete":"اكتمل الرفع",
    "Processing":"جارٍ المعالجة",
    "Uploading":"جارٍ الرفع",
    "Downloading":"جارٍ التحميل",
    "Preparing":"جارٍ التحضير",
    "Almost done":"يكاد ينتهي",
    "Cancel upload":"إلغاء الرفع",
    "Retry upload":"إعادة محاولة الرفع",
    "Network error":"خطأ في الشبكة",
    "Connection lost":"فُقد الاتصال",
    "Reconnect":"إعادة الاتصال",
    "Offline mode":"وضع عدم الاتصال",
    "You are offline":"أنت غير متصل",
    "Check your connection":"تحقق من اتصالك",
    "Server unreachable":"السيرفر غير متاح",
    "Gateway disconnected":"انقطع البوابة",
    "Session expired":"انتهت الجلسة",
    "Login again":"سجّل الدخول مجددًا",
    "Refresh page":"تحديث الصفحة",
    "Reload":"إعادة تحميل",
    "Force reload":"إعادة تحميل قسرية",
    "Clear cache":"مسح الذاكرة المؤقتة",
    "Reset settings":"إعادة تعيين الإعدادات",
    "Restore defaults":"استعادة الافتراضي",
    "Import settings":"استيراد الإعدادات",
    "Export settings":"تصدير الإعدادات",
    "Copy settings":"نسخ الإعدادات",
    "Paste settings":"لصق الإعدادات",
    "Settings saved":"تم حفظ الإعدادات",
    "Settings applied":"تم تطبيق الإعدادات",
    "No changes":"لا تغييرات",
    "Unsaved":"غير محفوظ",
    "Saved":"محفوظ",
    "Copied to clipboard":"تم النسخ",
    "Failed to copy":"فشل النسخ",
    "Clipboard":"الحافظة",
    "Paste from clipboard":"لصق من الحافظة",
    "Cut":"قص",
    "Undo":"تراجع",
    "Redo":"إعادة",
    "Find":"بحث",
    "Replace":"استبدال",
    "Find in conversation":"بحث في المحادثة",
    "Jump to message":"الانتقال للرسالة",
    "Jump to date":"الانتقال للتاريخ",
    "Jump to channel":"الانتقال للقناة",
    "Go to channel":"الذهاب للقناة",
    "Go to server":"الذهاب للسيرفر",
    "Go to message":"الذهاب للرسالة",
    "Open thread":"فتح الموضوع",
    "Close thread":"إغلاق الموضوع",
    "Thread settings":"إعدادات الموضوع",
    "Thread members":"أعضاء الموضوع",
    "Add people":"إضافة أشخاص",
    "Add People":"إضافة أشخاص",
    "Remove from thread":"إزالة من الموضوع",
    "Notify me":"أبلغني",
    "Stop notifying":"إيقاف الإشعار",
    "Watch thread":"متابعة الموضوع",
    "Unwatch thread":"إلغاء متابعة الموضوع",
    "Thread notifications":"إشعارات الموضوع",
    "All thread messages":"كل رسائل الموضوع",
    "Only @mentions in thread":"الإشارات فقط في الموضوع",
    "Nothing in thread":"لا شيء في الموضوع",
    "Forum post":"منشور المنتدى",
    "Forum posts":"منشورات المنتدى",
    "Post title":"عنوان المنشور",
    "Post body":"نص المنشور",
    "Add tag":"إضافة وسم",
    "Manage tags":"إدارة الوسوم",
    "Available tags":"الوسوم المتاحة",
    "Required tag":"وسم مطلوب",
    "Sort posts":"ترتيب المنشورات",
    "Latest activity":"آخر نشاط",
    "Creation date":"تاريخ الإنشاء",
    "Most reactions":"الأكثر تفاعلًا",
    "Guidelines":"الإرشادات",
    "Read guidelines":"اقرأ الإرشادات",
    "Post guidelines":"إرشادات النشر",
    "Tag":"وسم",
    "Tagged":"موسوم",
    "Untagged":"غير موسوم",
    "Q&A":"أسئلة وأجوبة",
    "Announcement posts":"منشورات الإعلانات",
    "Media posts":"منشورات الوسائط",
    "Text posts":"منشورات نصية",
    "Link posts":"منشورات روابط",
    "Poll posts":"منشورات استطلاع",
    "Create announcement":"إنشاء إعلان",
    "Publish announcement":"نشر إعلان",
    "Follow announcements":"متابعة الإعلانات",
    "Unfollow announcements":"إلغاء متابعة الإعلانات",
    "Crossposted":"أُعيد نشره",
    "Published":"نُشر",
    "Draft saved":"تم حفظ المسودة",
    "Autosave":"حفظ تلقائي",
    "Discard draft":"تجاهل المسودة",
    "Restore draft":"استعادة المسودة",
    "Edit draft":"تعديل المسودة",
    "Preview post":"معاينة المنشور",
    "Post now":"انشر الآن",
    "Schedule post":"جدولة المنشور",
    "Scheduled for":"مجدول لـ",
    "Edit schedule":"تعديل الجدولة",
    "Cancel schedule":"إلغاء الجدولة",
    "Reschedule":"إعادة الجدولة",
    "Posting":"جارٍ النشر",
    "Posted":"تم النشر",
    "Failed to post":"فشل النشر",
    "Character count":"عدد الأحرف",
    "Too many characters":"أحرف كثيرة جدًا",
    "Minimum length":"الحد الأدنى للطول",
    "Maximum length":"الحد الأقصى للطول",
    "Emoji reactions":"تفاعلات الإيموجي",
    "Super reactions available":"تفاعلات خارقة متاحة",
    "Unlock with boost":"افتح بالتعزيز",
    "Unlock with Nitro":"افتح بنايترو",
    "Reaction limit reached":"وصلت لحد التفاعلات",
    "Remove reaction":"إزالة التفاعل",
    "Remove all reactions":"إزالة كل التفاعلات",
    "View reactions":"عرض التفاعلات",
    "React with emoji":"تفاعل بإيموجي",
    "Add super reaction":"إضافة تفاعل خارق",
    "Burst reaction":"تفاعل انفجاري",
    "Who reacted":"من تفاعل",
    "Reaction details":"تفاصيل التفاعل",
    "Click to react":"انقر للتفاعل",
    "Hold to super react":"اضغط مطولًا لتفاعل خارق",
    "Sticker sent":"تم إرسال ملصق",
    "GIF sent":"تم إرسال GIF",
    "File sent":"تم إرسال ملف",
    "Voice message":"رسالة صوتية",
    "Video message":"رسالة فيديو",
    "Recording voice":"تسجيل صوت",
    "Recording video":"تسجيل فيديو",
    "Hold to record":"اضغط مطولًا للتسجيل",
    "Release to send":"أفلت للإرسال",
    "Slide to cancel":"اسحب للإلغاء",
    "Cancel recording":"إلغاء التسجيل",
    "Play voice message":"تشغيل الرسالة الصوتية",
    "Pause voice message":"إيقاف الرسالة الصوتية",
    "Transcribe":"نسخ نصي",
    "Transcription":"النسخ النصي",
    "Show transcription":"إظهار النسخ",
    "Hide transcription":"إخفاء النسخ",
    "Auto-transcribe":"نسخ تلقائي",
    "Translation unavailable":"الترجمة غير متاحة",
    "Could not translate":"تعذّرت الترجمة",
    "Translate message":"ترجمة الرسالة",
    "Original message":"الرسالة الأصلية",
    "Translated message":"الرسالة المترجمة",
    "Language detected":"تم اكتشاف اللغة",
    "Arabic":"العربية",
    "English, US":"الإنجليزية (أمريكا)",
    "English, UK":"الإنجليزية (بريطانيا)",
    "Interface Language":"لغة الواجهة",
    "Spellcheck":"التدقيق الإملائي",
    "Auto correct":"تصحيح تلقائي",
    "Suggest emojis":"اقتراح إيموجي",
    "Show emoji reactions":"إظهار تفاعلات الإيموجي",
    "Show sticker suggestions":"اقتراح الملصقات",
    "Inline preview":"معاينة مضمنة",
    "Link preview":"معاينة الرابط",
    "Rich embeds":"تضمينات غنية",
    "Compact mode":"الوضع المضغوط",
    "Show avatars":"إظهار الصور الرمزية",
    "Animate emoji":"تحريك الإيموجي",
    "Play animated emoji":"تشغيل إيموجي متحرك",
    "Render embeds":"عرض التضمينات",
    "Render reactions":"عرض التفاعلات",
    "Render stickers":"عرض الملصقات",
    "Use slash command":"استخدم أمر /",
    "Slash command":"أمر شرطة",
    "Command palette":"لوحة الأوامر",
    "Quick switcher":"التبديل السريع",
    "Search or create":"بحث أو إنشاء",
    "Create invite":"إنشاء دعوة",
    "User settings":"إعدادات المستخدم",
    "Channel topic":"موضوع القناة",
    "Edit channel topic":"تعديل موضوع القناة",
    "Set channel topic":"تعيين موضوع القناة",
    "No topic set":"لم يُعيّن موضوع",
    "Channel description":"وصف القناة",
    "Server description":"وصف السيرفر",
    "Edit description":"تعديل الوصف",
    "Add description":"إضافة وصف",
    "Character limit exceeded":"تجاوز حد الأحرف",
    "Name taken":"الاسم مستخدم",
    "Invalid name":"اسم غير صالح",
    "Name too long":"الاسم طويل جدًا",
    "Name too short":"الاسم قصير جدًا",
    "Reserved name":"اسم محجوز",
    "Profanity not allowed":"الألفاظ النابية غير مسموحة",
    "Contains blocked words":"يحتوي كلمات محظورة",
    "Try a different name":"جرّب اسمًا آخر",
    "Available":"متاح",
    "Unavailable":"غير متاح",
    "Taken":"مستخدم",
    "Checking availability":"جارٍ التحقق من التوفر",
    "Creating":"جارٍ الإنشاء",
    "Deleting":"جارٍ الحذف",
    "Updating":"جارٍ التحديث",
    "Saving":"جارٍ الحفظ",
    "Applying":"جارٍ التطبيق",
    "Loading more":"تحميل المزيد",
    "End of list":"نهاية القائمة",
    "No items":"لا عناصر",
    "Empty":"فارغ",
    "Empty inbox":"صندوق الوارد فارغ",
    "No mentions":"لا إشارات",
    "No notifications":"لا إشعارات",
    "All caught up":"أنت على اطلاع",
    "You're all caught up":"أنت على اطلاع بكل شيء",
    "Catch up":"الاطلاع",
    "Mark all as read":"تحديد الكل كمقروء",
    "Clear all notifications":"مسح كل الإشعارات",
    "Notification inbox":"صندوق الإشعارات",
    "Activity feed":"خلاصة النشاط",
    "Now Active":"نشط الآن",
    "Recently Played Games":"ألعاب لُعبت مؤخرًا",
    "No activity":"لا نشاط",
    "Start playing a game":"ابدأ لعبة",
    "Share your activity":"شارك نشاطك",
    "Activity sharing":"مشاركة النشاط",
    "Who can see":"من يمكنه الرؤية",
    "Share activity status":"مشاركة حالة النشاط",
    "Use large image":"استخدام صورة كبيرة",
    "Use small image":"استخدام صورة صغيرة",
    "Party size":"حجم الفريق",
    "Party ID":"معرّف الفريق",
    "Join secret":"سر الانضمام",
    "Spectate secret":"سر المشاهدة",
    "Match secret":"سر المباراة",
    "Discord Rich Presence":"حالة ديسكورد الغنية",
    "Connected accounts":"الحسابات المرتبطة",
    "Not connected":"غير مرتبط",
    "Link account":"ربط الحساب",
    "Account linked":"تم ربط الحساب",
    "Account unlinked":"تم فك ربط الحساب",
    "Sync contacts":"مزامنة جهات الاتصال",
    "Find friends":"البحث عن أصدقاء",
    "Invite contacts":"دعوة جهات الاتصال",
    "Share invite link":"مشاركة رابط الدعوة",
    "Share server":"مشاركة السيرفر",
    "Share channel":"مشاركة القناة",
    "Share message":"مشاركة الرسالة",
    "Share profile":"مشاركة الملف",
    "QR invite":"دعوة QR",
    "Scan to join":"امسح للانضمام",
    "Copy invite code":"نسخ رمز الدعوة",
    "Invite code":"رمز الدعوة",
    "Invalid code":"رمز غير صالح",
    "Code expired":"انتهى الرمز",
    "Too many uses":"استخدامات كثيرة",
    "Invite revoked":"أُلغيت الدعوة",
    "Invite paused":"الدعوة متوقفة",
    "Create another invite":"إنشاء دعوة أخرى",
    "Manage invites":"إدارة الدعوات",
    "Who created":"من أنشأ",
    "Created":"أُنشئ",
    "Expires in":"ينتهي خلال",
    "Never expires":"لا ينتهي",
    "Temporary":"مؤقت",
    "Permanent":"دائم",
    "Single use":"استخدام واحد",
    "Unlimited uses":"استخدامات غير محدودة",
    "Remaining uses":"الاستخدامات المتبقية",
    "Used":"مستخدم",
    "Times used":"مرات الاستخدام",
    "Last used":"آخر استخدام",
    "Created by":"أنشأه",
    "Invite settings":"إعدادات الدعوة",
    "Advanced invite":"دعوة متقدمة",
    "Vanity invite":"دعوة مخصصة",
    "Custom URL":"رابط مخصص",
    "URL taken":"الرابط مستخدم",
    "URL available":"الرابط متاح",
    "Copy vanity URL":"نسخ الرابط المخصص",
    "Requires boost level":"يتطلب مستوى تعزيز",
    "Requires Level 3":"يتطلب المستوى 3",
    "Unlock vanity URL":"فتح الرابط المخصص",
    "Server features":"مزايا السيرفر",
    "Feature locked":"الميزة مقفلة",
    "Feature unlocked":"الميزة مفتوحة",
    "Learn about boosts":"اعرف المزيد عن التعزيزات",
    "Compare plans":"قارن الخطط",
    "See all perks":"عرض كل المزايا",
    "What's included":"ما المشمول",
    "Popular perks":"مزايا شائعة",
    "Everything in Basic":"كل ما في بيسك",
    "Everything in Classic":"كل ما في كلاسيك",
    "Best for communities":"الأفضل للمجتمعات",
    "Best for friends":"الأفضل للأصدقاء",
    "Personal use":"استخدام شخصي",
    "Community use":"استخدام مجتمعي",
    "Start free trial":"بدء تجربة مجانية",
    "Free trial":"تجربة مجانية",
    "Trial ends":"تنتهي التجربة",
    "Cancel anytime":"إلغاء في أي وقت",
    "No commitment":"بدون التزام",
    "Billed monthly":"فوترة شهرية",
    "Billed yearly":"فوترة سنوية",
    "Save 16%":"وفر 16%",
    "Save 37%":"وفر 37%",
    "Most popular":"الأكثر شعبية",
    "Recommended plan":"الخطة الموصى بها",
    "Current subscription":"الاشتراك الحالي",
    "Manage plan":"إدارة الخطة",
    "Change subscription":"تغيير الاشتراك",
    "Cancel subscription":"إلغاء الاشتراك",
    "Resume subscription":"استئناف الاشتراك",
    "Subscription canceled":"تم إلغاء الاشتراك",
    "Subscription active":"الاشتراك نشط",
    "Payment failed":"فشل الدفع",
    "Update payment":"تحديث الدفع",
    "Payment method":"طريقة الدفع",
    "Add payment method":"إضافة طريقة دفع",
    "Remove payment method":"إزالة طريقة الدفع",
    "Default payment":"الدفع الافتراضي",
    "Billing address":"عنوان الفوترة",
    "Tax ID":"الرقم الضريبي",
    "Invoice history":"سجل الفواتير",
    "Download receipt":"تحميل الإيصال",
    "Refund requested":"طُلب استرداد",
    "Refund approved":"وُافق على الاسترداد",
    "Refund denied":"رُفض الاسترداد",
    "Contact billing support":"تواصل مع دعم الفوترة",
    "Gift sent":"تم إرسال الهدية",
    "Gift received":"تم استلام الهدية",
    "Redeem gift":"استبدال الهدية",
    "Gift link":"رابط الهدية",
    "Share gift":"مشاركة الهدية",
    "Gift expires":"تنتهي الهدية",
    "Choose gift":"اختر هدية",
    "Personalize gift":"تخصيص الهدية",
    "Add message":"إضافة رسالة",
    "Gift message":"رسالة الهدية",
    "Send gift":"إرسال الهدية",
    "Claim gift":"استلام الهدية",
    "Already claimed":"مُستلم مسبقًا",
    "Gift unavailable":"الهدية غير متاحة",
    "Wrong account":"حساب خاطئ",
    "Switch account":"تبديل الحساب",
    "Add account":"إضافة حساب",
    "Remove account":"إزالة الحساب",
    "Switch profiles":"تبديل الملفات",
    "Manage accounts":"إدارة الحسابات",
    "Quick switch":"تبديل سريع",
    "Account switcher":"مبدّل الحسابات",
    "Logged in as":"مسجّل كـ",
    "Not logged in":"غير مسجّل",
    "Guest mode":"وضع الضيف",
    "Preview mode":"وضع المعاينة",
    "Read-only mode":"وضع القراءة فقط",
    "Maintenance":"صيانة",
    "Under maintenance":"قيد الصيانة",
    "We'll be back soon":"سنعود قريبًا",
    "Service outage":"انقطاع الخدمة",
    "Status page":"صفحة الحالة",
    "All systems operational":"كل الأنظمة تعمل",
    "Partial outage":"انقطاع جزئي",
    "Major outage":"انقطاع كبير",
    "Degraded performance":"أداء منخفض",
    "Investigating":"قيد التحقيق",
    "Identified":"تم التحديد",
    "Monitoring":"مراقبة",
    "Resolved":"تم الحل",
    "Incident history":"سجل الحوادث",
    "Subscribe to updates":"اشترك في التحديثات",
    "RSS feed":"خلاصة RSS",
    "API status":"حالة API",
    "Voice status":"حالة الصوت",
    "Media status":"حالة الوسائط",
    "Push notifications status":"حالة إشعارات الدفع",
    "Search status":"حالة البحث",
    "Login status":"حالة تسجيل الدخول",
    "Registration status":"حالة التسجيل",
    "Captcha required":"يتطلب كابتشا",
    "Verify you are human":"تحقق أنك إنسان",
    "Complete captcha":"أكمل الكابتشا",
    "Captcha failed":"فشل الكابتشا",
    "Try again later":"حاول لاحقًا",
    "Too many attempts":"محاولات كثيرة",
    "Account rate limited":"الحساب محدود المعدل",
    "IP banned":"عنوان IP محظور",
    "Hardware banned":"جهاز محظور",
    "Phone banned":"هاتف محظور",
    "Email banned":"بريد محظور",
    "Appeal ban":"الاستئناف على الحظر",
    "Ban reason":"سبب الحظر",
    "Ban expires":"ينتهي الحظر",
    "Permanent ban":"حظر دائم",
    "Temporary ban":"حظر مؤقت",
    "Warning issued":"تم إصدار تحذير",
    "Final warning":"تحذير أخير",
    "Strike":"إنذار",
    "Strikes":"إنذارات",
    "Moderation action":"إجراء إشراف",
    "Moderation log":"سجل الإشراف",
    "Case ID":"رقم القضية",
    "Moderator note":"ملاحظة المشرف",
    "Public reason":"السبب العام",
    "Internal reason":"السبب الداخلي",
    "Evidence":"دليل",
    "Attach evidence":"إرفاق دليل",
    "Report ID":"رقم البلاغ",
    "Report status":"حالة البلاغ",
    "Report submitted":"تم إرسال البلاغ",
    "Under review":"قيد المراجعة",
    "Action taken":"تم اتخاذ إجراء",
    "No action taken":"لم يُتخذ إجراء",
    "Close report":"إغلاق البلاغ",
    "Reopen report":"إعادة فتح البلاغ",
    "Escalate report":"تصعيد البلاغ",
    "Safety tools":"أدوات الأمان",
    "Family controls":"ضوابط العائلة",
    "Teen account":"حساب مراهق",
    "Parent account":"حساب ولي",
    "Link family":"ربط العائلة",
    "Unlink family":"فك ربط العائلة",
    "Activity alerts":"تنبيهات النشاط",
    "Friend requests alerts":"تنبيهات طلبات الصداقة",
    "Message alerts":"تنبيهات الرسائل",
    "Server join alerts":"تنبيهات انضمام السيرفر",
    "Screen time":"وقت الشاشة",
    "Daily limit":"الحد اليومي",
    "Quiet hours":"ساعات الهدوء",
    "Allowed servers":"السيرفرات المسموحة",
    "Blocked servers":"السيرفرات المحظورة",
    "Allowed DMs":"الرسائل الخاصة المسموحة",
    "Restricted mode":"الوضع المقيّد",
    "Safe direct messaging":"رسائل خاصة آمنة",
    "Keep me safe":"أبقني آمنًا",
    "My friends are nice":"أصدقائي لطفاء",
    "Do not scan":"عدم الفحص",
    "Scan media from everyone":"فحص وسائط الجميع",
    "Scan media from non-friends":"فحص وسائط غير الأصدقاء",
    "Explicit media filter":"فلتر الوسائط الصريحة",
    "Block explicit images":"حظر الصور الصريحة",
    "Blur explicit images":"تمويه الصور الصريحة",
    "Show explicit content":"إظهار المحتوى الصريح",
    "Age gate":"بوابة العمر",
    "Confirm age":"تأكيد العمر",
    "You must be 13+":"يجب أن يكون عمرك 13+",
    "You must be 18+":"يجب أن يكون عمرك 18+",
    "Age verification failed":"فشل التحقق من العمر",
    "Region restricted":"مقيّد إقليميًا",
    "Not available in your region":"غير متاح في منطقتك",
    "Coming soon":"قريبًا",
    "New feature":"ميزة جديدة",
    "Try it":"جرّبه",
    "Enable beta":"تفعيل التجريبي",
    "Disable beta":"تعطيل التجريبي",
    "Beta features":"ميزات تجريبية",
    "Labs":"المختبرات",
    "Experiments":"تجارب",
    "Staff settings":"إعدادات الموظفين",
    "Internal tools":"أدوات داخلية",
    "Copy build number":"نسخ رقم البناء",
    "Build number":"رقم البناء",
    "Canary":"كاناري",
    "PTB":"PTB",
    "Stable":"مستقر",
    "Development":"تطوير",
    "Localhost":"محلي",
    "Environment":"البيئة",
    "Production":"إنتاج",
    "Staging":"تجريبي",
    "Switch branch":"تبديل الفرع",
    "Reload with cache":"إعادة تحميل مع الذاكرة",
    "Open DevTools":"فتح أدوات المطور",
    "Toggle DevTools":"تبديل أدوات المطور",
    "Inspect element":"فحص العنصر",
    "View source":"عرض المصدر",
    "Console":"وحدة التحكم",
    "Network":"الشبكة",
    "Performance":"الأداء",
    "Memory":"الذاكرة",
    "Application":"التطبيق",
    "Storage":"التخزين",
    "IndexedDB":"IndexedDB",
    "Local Storage":"التخزين المحلي",
    "Session Storage":"تخزين الجلسة",
    "Cookies":"ملفات تعريف الارتباط",
    "Clear site data":"مسح بيانات الموقع",
    "Revoke tokens":"إلغاء الرموز",
    "Regenerate token":"إعادة توليد الرمز",
    "Bot token":"رمز البوت",
    "Public key":"المفتاح العام",
    "Permissions integer":"رقم الصلاحيات",
    "Copy permissions":"نسخ الصلاحيات",
    "Permission calculator":"حاسبة الصلاحيات",
    "Role hierarchy":"تسلسل الرتب",
    "Drag to reorder":"اسحب لإعادة الترتيب",
    "Move up":"تحريك لأعلى",
    "Move down":"تحريك لأسفل",
    "Move to top":"نقل للأعلى",
    "Move to bottom":"نقل للأسفل",
    "Duplicate role":"نسخ الرتبة",
    "Copy role":"نسخ الرتبة",
    "Role color":"لون الرتبة",
    "Gradient roles":"رتب متدرجة",
    "Role icon":"أيقونة الرتبة",
    "Upload role icon":"رفع أيقونة الرتبة",
    "Display separately":"عرض بشكل منفصل",
    "Allow anyone to mention":"السماح للجميع بالإشارة",
    "View server as role":"عرض السيرفر كرتبة",
    "View as":"عرض كـ",
    "Exit view as":"الخروج من العرض كـ",
    "Preview as member":"معاينة كعضو",
    "Preview permissions":"معاينة الصلاحيات",
    "Effective permissions":"الصلاحيات الفعلية",
    "Denied permissions":"الصلاحيات المرفوضة",
    "Allowed permissions":"الصلاحيات المسموحة",
    "Neutral permissions":"صلاحيات محايدة",
    "Overwrite permissions":"تجاوز الصلاحيات",
    "Reset permissions":"إعادة تعيين الصلاحيات",
    "Clear overwrites":"مسح التجاوزات",
    "Apply to all channels":"تطبيق على كل القنوات",
    "Apply to category":"تطبيق على الفئة",
    "Private category":"فئة خاصة",
    "Public category":"فئة عامة",
    "Collapse category":"طي الفئة",
    "Expand category":"توسيع الفئة",
    "Mute category":"كتم الفئة",
    "Unmute category":"إلغاء كتم الفئة",
    "Notification override for category":"تجاوز إشعارات الفئة",
    "Channel order":"ترتيب القنوات",
    "Drag channels":"اسحب القنوات",
    "Drop to reorder":"أفلت لإعادة الترتيب",
    "Cannot move channel":"لا يمكن نقل القناة",
    "Cannot delete category with channels":"لا يمكن حذف فئة فيها قنوات",
    "Delete category only":"حذف الفئة فقط",
    "Delete category and channels":"حذف الفئة والقنوات",
    "Archive instead":"أرشفة بدلًا من ذلك",
    "Keep channels":"الإبقاء على القنوات",
    "Move channels to":"نقل القنوات إلى",
    "Uncategorized":"غير مصنّف",
    "No category":"بدون فئة",
    "Create in category":"إنشاء في الفئة",
    "Voice channels":"القنوات الصوتية",
    "Text channels":"القنوات النصية",
    "Announcement channels":"قنوات الإعلانات",
    "Forum channels":"قنوات المنتدى",
    "Stage channels":"قنوات الستيج",
    "Media channels":"قنوات الوسائط",
    "Directory channels":"قنوات الدليل",
    "Linked channels":"قنوات مرتبطة",
    "Followed channel":"قناة متابَعة",
    "Publishing":"النشر",
    "Publish to":"النشر إلى",
    "Connected channel":"قناة متصلة",
    "Disconnect channel":"فصل القناة",
    "News follower":"متابع الأخبار",
    "Announcement follower":"متابع الإعلانات",
    "Crosspost failed":"فشل إعادة النشر",
    "Crosspost successful":"نجح إعادة النشر",
    "Requires announce permission":"يتطلب صلاحية الإعلان",
    "Webhook message":"رسالة خطاف",
    "Bot message":"رسالة بوت",
    "System notification":"إشعار نظام",
    "Call message":"رسالة مكالمة",
    "Boost message":"رسالة تعزيز",
    "Integration message":"رسالة تكامل",
    "Stage start":"بدء الستيج",
    "Stage end":"انتهاء الستيج",
    "Event start":"بدء الفعالية",
    "Event end":"انتهاء الفعالية",
    "Thread created":"تم إنشاء الموضوع",
    "Thread archived":"تم أرشفة الموضوع",
    "Role added":"أُضيفت رتبة",
    "Role removed":"أُزيلت رتبة",
    "Nickname changed":"تغيّر اللقب",
    "Avatar changed":"تغيّرت الصورة الرمزية",
    "Banner changed":"تغيّرت اللافتة",
    "Server name changed":"تغيّر اسم السيرفر",
    "Server icon changed":"تغيّرت أيقونة السيرفر",
    "Channel renamed":"أُعيد تسمية القناة",
    "Permission updated":"حُدّثت الصلاحيات",
    "Emoji added":"أُضيف إيموجي",
    "Emoji removed":"أُزيل إيموجي",
    "Sticker added":"أُضيف ملصق",
    "Sticker removed":"أُزيل ملصق",
    "Sound added":"أُضيف صوت",
    "Sound removed":"أُزيل صوت",
    "Integration added":"أُضيف تكامل",
    "Integration removed":"أُزيل تكامل",
    "Webhook created":"أُنشئ خطاف",
    "Webhook deleted":"حُذف خطاف",
    "Invite created":"أُنشئت دعوة",
    "Invite deleted":"حُذفت دعوة",
    "Member joined":"انضم عضو",
    "Member left":"غادر عضو",
    "Member kicked":"طُرد عضو",
    "Member banned":"حُظر عضو",
    "Member unbanned":"أُلغي حظر عضو",
    "Message deleted":"حُذفت رسالة",
    "Message pinned":"ثُبّتت رسالة",
    "Message unpinned":"أُلغي تثبيت رسالة",
    "Bulk delete":"حذف جماعي",
    "Purge messages":"تطهير الرسائل",
    "Delete messages":"حذف الرسائل",
    "Delete all messages":"حذف كل الرسائل",
    "Delete and ban":"حذف وحظر",
    "Soft ban":"حظر لين",
    "Hard ban":"حظر قاسٍ",
    "Hackban":"حظر عن بُعد",
    "Unban":"إلغاء الحظر",
    "Ban appeal":"استئناف الحظر",
    "View ban reason":"عرض سبب الحظر",
    "Ban log":"سجل الحظر",
    "Active bans":"الحظر النشط",
    "Expired bans":"الحظر المنتهي",
    "Search bans":"بحث في الحظر",
    "No bans":"لا حظر",
    "No members":"لا أعضاء",
    "No channels":"لا قنوات",
    "No roles":"لا رتب",
    "No emojis":"لا إيموجي",
    "No stickers":"لا ملصقات",
    "No sounds":"لا أصوات",
    "No webhooks":"لا خطافات",
    "No integrations":"لا تكاملات",
    "No events":"لا فعاليات",
    "No threads":"لا مواضيع",
    "No posts":"لا منشورات",
    "No invites":"لا دعوات",
    "No apps":"لا تطبيقات",
    "No results":"لا نتائج",
    "No matches":"لا تطابقات",
    "No data":"لا بيانات",
    "Nothing here":"لا شيء هنا",
    "Try searching":"جرّب البحث",
    "Refine your search":"حسّن بحثك",
    "Search tips":"نصائح البحث",
    "From:user":"من:مستخدم",
    "In:channel":"في:قناة",
    "Has:link":"يحتوي:رابط",
    "Has:image":"يحتوي:صورة",
    "Has:video":"يحتوي:فيديو",
    "Has:file":"يحتوي:ملف",
    "Has:embed":"يحتوي:تضمين",
    "Has:sticker":"يحتوي:ملصق",
    "Before:date":"قبل:تاريخ",
    "After:date":"بعد:تاريخ",
    "During:date":"خلال:تاريخ",
    "Pinned:true":"مثبّت:نعم",
    "Mentions:me":"إشارات:أنا",
    "Search filters":"فلاتر البحث",
    "Filter by":"تصفية حسب",
    "Date range":"نطاق التاريخ",
    "Has attachment":"يحتوي مرفق",
    "Has link":"يحتوي رابط",
    "From user":"من مستخدم",
    "In channel":"في قناة",
    "Search in":"البحث في",
    "This server":"هذا السيرفر",
    "All servers":"كل السيرفرات",
    "Direct messages":"الرسائل الخاصة",
    "Message content":"محتوى الرسالة",
    "Author":"الكاتب",
    "Channel":"القناة",
    "Server":"السيرفر",
    "Timestamp":"الوقت",
    "Relevance score":"درجة الصلة",
    "Exact match":"تطابق تام",
    "Partial match":"تطابق جزئي",
    "Did you mean":"هل تقصد",
    "Showing results for":"عرض نتائج لـ",
    "Search instead for":"ابحث بدلًا عن",
    "Clear search":"مسح البحث",
    "Recent searches":"عمليات بحث حديثة",
    "Popular searches":"عمليات بحث شائعة",
    "Saved searches":"عمليات بحث محفوظة",
    "Save search":"حفظ البحث",
    "Delete search":"حذف البحث"
    
    };

        this.translatePage();

        this.observer = new MutationObserver(() => this.translatePage());
        this.observer.observe(document.body, {
            childList: true,
            subtree: true
        });

        BdApi.UI.showToast("Discord Arabic Translator is enabled", { type: "success" });
    }

    stop() {
        if (this.observer) {
            this.observer.disconnect();
            this.observer = null;
        }
    }
};
